#! /bin/bash
#
# Converts a Gaai records file into a pcap file for viewing with Wireshark and fuut.
# $1: name of file containing the records generated by Gaai.
#
# CDR records are mapped to DLT_USER0 (DLT=147)
# CCDT records are mapped to DLT_USER1 (DLT=148)
# EVENT records are mapped to DLT_USER2 (DLT=149)
# METRIC records are mapped to DLT_USER3 (DLT=150)


if [ -f "$1" ]; then
  echo "$1 is a file"
  DLTNum=147
  case "$1" in
   *_CDR_*)
     DLTNum=147
     ;;
   *_CCDT_*)
     DLTNum=148
     ;;
   *_EVENT_*)
     DLTNum=149
     ;;
   *_METRIC_*)
     DLTNum=150
     ;;
  esac
  echo "Found DLTNum=$DLTNum" 
  cat $1 | sed -e 's/.*://' | sed 's/.\{2\}/& /g'  | sed 's/^/000000 /' | text2pcap -l $DLTNum - "${1%.*}.pcap"
else 
  echo "$1 is not a file"
fi
